//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperNumero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class numeros
    {
        public int idNumero { get; set; }
        public string numero { get; set; }
        public int resultado { get; set; }
        public string detalle { get; set; }
        public Nullable<System.DateTime> fechayhora { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaNueva { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
